### ISSUE TITLE
Michael möchte REST Bewerbung über Personio

### ISSUE THREAD

**Issue by ChrisKofler** [Gepardec/weckdengeparden#2]
zusätzliche Felder (siehe https://www.gepardec.com/job/requirements-engineer-analyst-m-w/, wenn ma  auf "bewerben" clickt)
* title (optional)
* xingLink (optional)
* linkedinLink (optional)
* source (optional)
![image](https://user-images.githubusercontent.com/20546046/70054177-494a9d00-15d7-11ea-918c-8a0bc1fef8be.png)
* otherSource (optional)

**Akzeptanzkritieren**
* Felder sind in der Schnittstelle ergänzt
* System schickt Bewerbungen über API nach Personio
* Email-Integration ist aus dem Code entfernt.
* Doku aktualisiert

**Comment by ChrisKofler** [comment]
Mit denselben Feldern wie die Bewerbung über die Website.

**Comment by cchet** [comment]
Und wie?

**Comment by ChrisKofler** [comment]
; )
@msollberger organisiert die Schnittstellen-Doku ... Die Anbindungen haben wir ja auch schon auf unserer Website.

**Comment by GuenterPirklbauer** [comment]
https://support.personio.de/hc/de/articles/360000314338-Die-Personio-Recruiting-API

**Comment by cchet** [comment]
@msollberger @GuenterPirklbauer 
Ich brauche eine Standard JobId auf die sich die Bewerber über den weckdengeparden service bewerben, nachdem sie ja keine Auswahl haben.
Vielleicht legst du eine JobId an für den weckdengeparden service, dann hast du die Bewerbungen auch immer schön gebündelt.

**Comment by cchet** [comment]
@ChrisKofler @msollberger 
Ist in einem Openshift Testprojekt deployed. 
Bitte mit Doku und Fehleingaben testen. Ich habe Validierung für die Requests auch eingebaut.

https://weckdengeparden-57-services-test.cloud.itandtel.at/

**Comment by ChrisKofler** [comment]
Bekomme die Meldung, dass der CV zu groß ist - hat aber nur 1 MB.
Und ich bekomme die Meldung, dass ich keine "answer" provided hab - hab ich aber.

![image](https://user-images.githubusercontent.com/20546046/72077779-21e2a080-32f8-11ea-985b-aaafb098fcb3.png)

**Comment by ChrisKofler** [comment]
Die Meldungen entsprechen damit textuell nicht mehr den ursprünglichen Anforderungen (und der Doku). Die Idee - es soll einfach ein wenig locker rüberkommen, die Welt ist eh zu ernst.

Statt: "You haven't provided an answer" => "Hm ... da fehlt die Antwort."
Statt "You CV is too large" => "Hey, dein CV ist zu fett. Reduzier ihn bitte auf unter 10 MB."

usw.

**Comment by cchet** [comment]
@ChrisKofler 
Die CV Größe ist jetzt auf 10Mb beschränkt.
Die Messages kannst du am Branch *feature/personio* anpassen [ValidationMessages.properties](https://github.com/Gepardec/weckdengeparden/blob/feature/personio/src/main/resources/ValidationMessages.properties).

**Comment by cchet** [comment]
> Bekomme die Meldung, dass der CV zu groß ist - hat aber nur 1 MB. Und ich bekomme die Meldung, dass ich keine "answer" provided hab - hab ich aber. ![image](https://user-images.githubusercontent.com/20546046/72077779-21e2a080-32f8-11ea-985b-aaafb098fcb3.png)

Ich sehe am Image nicht die gesamte Antwort, aber mit der Fehlermeldung ist gemeint, dass keine Antwort (der Property) bereitgestellt wurde.

**Comment by ChrisKofler** [comment]
{
   "firstName": "Chris",
   "lastName": "Kofler",
   "email": "christoph.kofler@gepardec.com",
   "phone": "0664/88231521",
   "challengeId": 1,
   "challengeAnswer": "50",
   "messageToGepardec": "Griass di, des is a Test!",
   "cv": "JVBERi0xLjcNCi
      ....  CV zu groß für den Git Comment .... SVFT0Y="
}

Es ist derselbe Request, der in der alten Version funktioniert hat.

>

**Comment by cchet** [comment]
Ist auf prod deployed
