### ISSUE TITLE
Michael möchte Bewerbungen dem richtigen Job in Personio zugeordnet haben

### ISSUE THREAD

**Issue by ChrisKofler** [Gepardec/weckdengeparden#4]
Wie

- [x] @msollberger In der Stellenanzeige auf gepardec.com wird die jobId textuell angezeigt 
- [x] @ChrisKofler Doku in Git ergänzen 
- [x] @mario-oberwalder , @andreas-repo Erweiterung des Interfaces um "jobId" (Integer, required)
- [x] @cchet Code Review, Unterstützung bei Deployment in OpenShift

**Comment by cchet** [comment]
@msollberger @ChrisKofler 
Änderungen am Branch **feature/4** eingecheckt und am Testsysteem deployed.

https://weckdengeparden-57-services-test.cloud.itandtel.at/

**Comment by ChrisKofler** [comment]
@mario-oberwalder , @andreas-repo : ich hab zu spät gecheckt, dass Thomas das bereits implementiert hat. Bitte seht euch den Code tortzdem an und bekommt ihn zum Laufen.

**Comment by cchet** [comment]
Ist fertig und deployed. @msollberger Anzeige der JobId im Formular ist noch ausständig

**Comment by msollberger** [comment]
erl.
