### ISSUE TITLE
RESTEASY004655 Fehler analysieren

### ISSUE THREAD

**Issue by ChrisKofler** [Gepardec/weckdengeparden#45]
Bsp. Ticket https://github.com/Gepardec/Internals/issues/380

Akzeptanzkritieren
* Fehlerverhalten ist klar
* Tickets sind aufgeräumt
* Lösungsidee vorhanden

**Comment by ChrisKofler** [comment]
Start: 10:30, 25.8.2020

**Comment by philzelinger** [comment]
Hiermit wird auch der Fehler 502 - Gateway currently unavailable behandelt.

Fehlerverhalten ist klar: Bei der Verbindung von unserem Service (ITandTel) und Personio, tritt während dem SSL Handshake ein Abbruch auf.

Tickets sind aufgeräumt

Lösung: Log wird erweitert, das der komplette Stacktrace geloggt wird. Und mit Issue #46 werden dann die alten Issues automatisch geschlossen, somit kein handlungsbedarf mehr

**Comment by philzelinger** [comment]
Ende: 12:00, 25.8.2020

**Comment by philzelinger** [comment]
Anfrage bezüglich der Timeouts bei Personio gestellt.

**Comment by philzelinger** [comment]
Bei Postman wurde der Rertry after Failure auf 1 gesetzt
