### ISSUE TITLE
Bewerber möchte sprechende Fehlermeldung wenn JobID in der Antwort fehlt

### ISSUE THREAD

**Issue by ChrisKofler** [Gepardec/weckdengeparden#5]
Aktuelle Fehlermeldung: "Sorry, something went wrong ..."

Gewünschte Fehlermeldung: "Bitte gib eine JobID an! (Hint: die steht auf der Website  unter dem Jobtitel)"

**Comment by cchet** [comment]
@ChrisKofler 
Der Fehler tritt auf wenn di JobId ungültig ist und nicht wenn sie nicht gesetzt ist.

**Comment by cchet** [comment]
Ist gefixed und deployed auf test, prod
