### ISSUE TITLE
Broken Projekt MVP

### ISSUE THREAD

**Issue by ChrisKofler** [Gepardec/weckdengeparden#62]
1. Beschreibung des Inhalts

Maven (zb PlugIn)

              Quarkus

              Java – Junit

              microprofil

              CV upload, success -> bewerbung

              code schreiben

              test gegen referenzsystem

              level

... Minimale Umsetzung via Umfrage.
Ziel: 30 Rückmeldungen, davon 50% über "5" auf der Skala von 1-10 bei den Kriterien lustig, nerdig, herausfordernd.

**Comment by agnesHi** [comment]
[Umfrage IT-Projekt SE.pdf](https://github.com/Gepardec/weckdengeparden/files/5516099/Umfrage.IT-Projekt.SE.pdf)

Ergebnisse der ersten Umfrage
