### ISSUE TITLE
Michael möchte mehr Infos zur Bewerbung erhalten

### ISSUE THREAD

**Issue by msollberger** [Gepardec/weckdengeparden#7]
1. "messageToGepardec": "<OPTIONAL_YOUR_MESSAGE_TO_GEPARDEC>" soll ein Pflichtfeld werden.
Beschreibung: "Why gepardec?"

2. "source": "<OPTIONAL_SOURCE>" soll ein Pflichtfeld werden.
Dropdown: Google, Stackoverflow, LinkedIn, Xing, karriere.at
Dropdown mit Text: Events, Recommendation, Other

**Comment by cchet** [comment]
@msollberger  @ChrisKofler 
Ist implementiert und wenn ItAndTel cloud wieder geht, dann wird es auf das Testsystem deployed und ist dann ready zum Testen.

**Comment by cchet** [comment]
@msollberger @ChrisKofler 
Ist auf Testsystem deployed 

https://weckdengeparden-57-services-test.cloud.itandtel.at

**Comment by cchet** [comment]
@ChrisKofler @msollberger 
Schon getestet?

**Comment by ChrisKofler** [comment]
Ich kann grad nichts testen, da ich auf meim Laptop nichts installieren kann.
Wenn du dafür Tests geschrieben hast, passt das für mich genauso in diesem Fall.
