### ISSUE TITLE
Einfache Aufgabe als Köder mit eingebauter Falle

### ISSUE THREAD

**Issue by agnesHi** [Gepardec/weckdengeparden#71]
Akzeptanzkriterien:

- Simple Aufgabe die aber einen Umweg(Fix) zur Lösung braucht
- "Verschachtelte Methoden"

**Comment by ChrisKofler** [comment]
nicht umsetzen, da der Umfang von BrokenProjekt zeitlich bereits ausreichend ist für unsere potentiellen Bewerber.
